import turtle
tina = turtle.Turtle(shape=”turtle”)
tina.up()
tina.forward(150)
tina.down()
tina.circle(25)
tina.up()
tina.left(180)
tina.forward(150)
tina.right(180)
tina.down()
tina.circle(50)
tina.up()
tina.left(180)
tina.forward(150)
tina.right(180)
tina.down()
tina.circle(100)
